name: Release

on:
  release:
    types: [published]

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Cache target folder
        uses: actions/cache@v3
        env:
          cache-name: target-folder
        with:
          path: target
          key: x86_64-linux-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            x86_64-linux-

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace --locked --release

      - name: Strip and rename binary
        run: strip target/release/jellyfin-rpc && mv target/release/jellyfin-rpc target/release/jellyfin-rpc-x86_64-linux

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --locked

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/jellyfin-rpc-x86_64-linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ubuntu-arm:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Setup Alpine Linux v3.15 for armv7
        uses: jirutka/setup-alpine@v1
        with:
          arch: armv7
          branch: v3.15
          packages: binutils
  
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          default: true
          override: true
  
      - name: Install ARM gcc
        run: sudo apt install gcc-arm-linux-gnueabihf -y
  
      - name: Cache target folder
        uses: actions/cache@v3
        env:
          cache-name: target-folder
        with:
          path: target
          key: arm-linux-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            arm-linux-
  
      - name: Build for ARM Linux
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target armv7-unknown-linux-gnueabihf --workspace --locked --release
  
      - name: Strip and rename binary
        run: strip target/armv7-unknown-linux-gnueabihf/release/jellyfin-rpc && mv target/armv7-unknown-linux-gnueabihf/release/jellyfin-rpc target/armv7-unknown-linux-gnueabihf/release/jellyfin-rpc-arm-linux
        shell: alpine.sh {0}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/armv7-unknown-linux-gnueabihf/release/jellyfin-rpc-arm-linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Cache target folder
        uses: actions/cache@v3
        env:
          cache-name: target-folder
        with:
          path: target
          key: x86_64-windows-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            x86_64-windows-

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace --locked --release

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --locked

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/jellyfin-rpc.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  macos-x86_64:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Cache target folder
        uses: actions/cache@v3
        env:
          cache-name: target-folder
        with:
          path: target
          key: x86_64-macos-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            x86_64-macos-

      - name: Build for x86_64 macOS
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace --locked --release

      - name: Strip and rename binary
        run: strip target/release/jellyfin-rpc && mv target/release/jellyfin-rpc target/release/jellyfin-rpc-x86_64-darwin

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --locked

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/jellyfin-rpc-x86_64-darwin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  macos-arm64:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
          default: true
          override: true

      - name: Cache target folder
        uses: actions/cache@v3
        env:
          cache-name: target-folder
        with:
          path: target
          key: arm64-macos-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            arm64-macos-

      - name: Build for arm64 macOS
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target aarch64-apple-darwin --workspace --locked --release

      - name: Strip and rename binary
        run: strip target/aarch64-apple-darwin/release/jellyfin-rpc && mv target/aarch64-apple-darwin/release/jellyfin-rpc target/aarch64-apple-darwin/release/jellyfin-rpc-arm64-darwin

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/aarch64-apple-darwin/release/jellyfin-rpc-arm64-darwin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
